name: Example workflow
on:
  workflow_dispatch
jobs:
  upload-logs-to-elastic:
    runs-on: ubuntu-latest
    needs: run-demo-app
    if: always()
    steps:
    - name: Upload GitHub Action workflows logs to elastic
      uses: shahargl/upload-github-workflow-logs-to-elastic@1.0.13
      with:
        github_token: "${{ secrets.GITHUB }}"
        github_org: "jaibwtl"
        github_repository: "website09"
        github_run_id: "${{ github.run_id }}"
        elastic_host: "http://ec2-54-202-44-207.us-west-2.compute.amazonaws.com:8080"
        elastic_api_key_id: "default"
        elastic_api_key: "default"
        elastic_index: "ci-cd"
  run-demo-app:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'
        token: ${{ secrets.GITHUB }}
    - name: Set up Python 3.11.1
      uses: actions/setup-python@v2
      with:
        python-version: '3.11.1'
    - name: Run script that echo outputs
      run: python main.py
